### ISSUE TITLE
Executable for the language server

### ISSUE THREAD

**Issue by williamboman** [microsoft/azure-pipelines-language-server#145]
Hello! Would it be possible to [add an executable](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin) to the language server package? See https://github.com/microsoft/compose-language-service/issues/114 for another example of this being added.

**Comment by 50Wliu** [comment]
Hey @williamboman, I see you've already discovered #107. How much do you expect this code will need to be changed in the future? Will it require regular (or even not-so-regular) maintenance, or is it an "add once and it should work forever™" kind of situation?

I'm not against adding an executable, but since azure-pipelines-vscode bundles the server directly and doesn't need to use the executable, this isn't really a feature we'll be able to maintain or provide support for.

**Comment by williamboman** [comment]
Generally, VSCode-based language server implementations just need to be a one-liner executable. Something like this should be enough:

- https://github.com/yioneko/vtsls/blob/main/packages/server/bin/vtsls.js
- https://github.com/yioneko/vtsls/blob/main/packages/server/package.json#L10-L12

**Comment by 50Wliu** [comment]
Thanks. Could you please create a PR?
